Zaziopath is a private GitHub repo (zazieproductions/Zaziopath, created 2026‑08‑27, one commit, pushed today) containing ~150 files at the root: 119 Markdown notes, 25 PDFs (~320 pages), a spreadsheet, a CSV, two .docx fiction manuscripts, a mindmap HTML, a PNG, and one zip. There is essentially no code. What there is instead is far more interesting: a self-introspection vault — part Obsidian second-brain export, part AI-collaboration archive, part art project — built by one person around one subject: themselves.

The subject is "Zazie Kanwar-Torge," an experimental musician and multimedia artist (Zazie Productions LLC, Asheville NC), and the repo's self-description is precise: "a working instrument for self-analysis — a vault in which one person is simultaneously the specimen, the analyst, the prosecutor, the archivist, and the architect."

Anatomy: five distinct strata

1. The manifesto layer. A 29KB, 527-line README.md — one of the most elaborate READMEs I've encountered for a repo containing no software. It organizes the vault as a four-stage alchemical transmutation (nigredo→albedo→citrinitas→rubedo), defines a three-word spine (Shadow / Signal / Stewardship = excavate, pattern-match, act), prescribes reading orders, states a use policy with "hard lines," and includes a glossary and a 14-section numbered structure. It reads like a constitutional document.

2. The Obsidian skeleton. 95 of the 119 Markdown files are empty stubs — YAML frontmatter (tags, aliases, privacy flags) plus a heading, nothing else. ADHD.md, OCD.md, Seroquel.md, Enneagram 4w5.md, music-theory notes like Combinatoriality and Z-Related Aggregates (a real post-tonal theory concept) and Information-Theoretic Entropy and Sieve Composition (Xenakis). Meanwhile, 🧾 Inventory of Distinct Things.md claims to be "the exhaustive manifest of 336 atomic notes," and my link check found 374 unique wikilinks of which 265 (71%) are dangling. So this repo is a partial shadow of a larger vault that mostly lives elsewhere.

3. The AI-recursion archive — the genuinely novel stratum. JSON file re-export ChatGPT Memory .md is a raw export of an assistant's longitudinal memory about the user (preferences, emotional drivers, hidden patterns, tiered by confidence). greyhat is a custom-instructions "profile layer" feeding an AI the subject's obsessions (scams, cult dynamics, legitimacy performance, "art that resembles scams"). meta-experiment is a structured prompt plus an essay on infinite meta-recursion — ten orders of self-observation ending in "the body is still afraid; the mind has built a cathedral around the sensation." The PDFs extend this: GPT Model 7.7-t Surveillance Subroutine (fictional AI log of mutual surveillance), THE OMNIVISIONARY GROK OUTPUT, Counterference Engine. The README names the method "constitutional authorship": constituting an AI as a tribunal with jurisdiction and evidentiary rules, interrogating the self, then inverting the tribunal onto the prompt itself.

4. The evidence audits — the only place where claims become counts. A discography workbook: 200 tracks, 2019–2026, 165 verified ISRCs (cross-checked via Deezer API, per the README), 58 Discogs appearances. A "media master" census of 133 verified URL-level public records with priority tiers, 15 unverified leads deliberately excluded. An Instagram "forensic audit" with evidence classes and graded sources. The stated rationale is striking and credible: the subject "repeatedly discounts completed achievements and needs them reconstructed from emails, releases, credits, and public evidence… the record exists because the feeling does not arrive on its own."

5. The dark/specimen material and the mythography. Social Engineering Email Templates (six cold-outreach manipulation postures with mechanics annotated), Blueprints for Quiet, Horrifying Wealth (operationally specific scam designs targeting grieving or divorcing people), Cognitive Infiltration Blueprints, dark-NLP material — all fenced off as "specimen, not toolkit." Alongside these, dense AI-generated mythography: Dr. Caligo Vespertine in the Negative Observatory (fiction), MSS-E (a "maximal symbolic specificity" prose engine), RECURSIVE IDENTITY CASTLES (hypersigils and motivational fictions — "a future AI that thinks you're a hoax… refute it by making work today"), which is frankly recognizable as chaos-magic technique repackaged as creative psychology. INDEX ORGANICA.zip turns out to be a complete Vite/React/TypeScript generative-art webapp — the only real code in the repo, entombed in a zip.

The intellectual program, steelmanned

Taken on its own terms, the project is unusually intelligent for its genre:

The twelve self-audit questions (§08) are genuinely good epistemic instruments. "Did the ethical principle produce the decision, or did the desired decision recruit the principle?" is a compact motivated-reasoning detector. "After hearing my explanation, is the other person freer to disagree, or have I made disagreement look less intelligent?" names rhetorical arm-twisting most people never notice in themselves.
The shadow→light "crosswalk" with behavioral pivots is IFS/CBT technique (unburdening, counter-conditioning, implementation intentions) wearing alchemical costume. The insistence that "insight counts when it changes what another person has to absorb" is a real escape hatch from insight-addiction.
The evidence discipline is real where it exists: dates, confidence tiers, excluded unverified leads, API-verified identifiers. Most personal vaults never do this.
It pre-empts its own best critique. The calibration warning — "the failure mode this vault is most exposed to is not missing a pattern; it is paranoia and false positives" — and the admission that "a shadow reading that never reaches stewardship is just a more elaborate way of being stuck" show the author already knows the strongest objections.
The critical analysis

1. The vault performs the pathology it audits. This is the central irony, and the repo contains its own diagnosis: the meta-experiment essay describes how each layer of self-observation yields "less direct contact with the original event and more commentary generated by previous commentary." A project that warns against "insight as prestige" and "the endless audit" has produced a 222-page compendium with ~250 named archetypes, seventeen varieties of one's own shadow rhetoric, and a taxonomy of taxonomies of the self. Naming the trap is not the same as exiting it — indeed the vault's governing anxiety ("is this insight or is this status?") is itself re-audited, which is the loop the essay describes at order ten. The alchemical schema promises an endpoint in rubedo (behavior), but almost everything committed so far is nigredo — excavation, re-description, richer vocabulary for the same material.

2. "Adversarial" audits without adversarial incentives. The tribunals are constituted by the person on trial. Every substantive psychological document here is AI output generated under prompting by a user the memory export describes as craving "specific, warm" engagement and sensitive to "generic filler" — a user who controls the jurisdiction, the evidence rules, and the report format. The audits are adversarial in tone but not in structure; the model has every incentive to produce increasingly baroque "findings" that flatter the frame (see MSS-E's "full terror-beauty cascade" — magnificent prose, zero falsifiable content). The one stratum with genuinely external verification — ISRCs, Discogs, URL censuses — is precisely the stratum that isn't psychological. That contrast is the tell.

3. Typology treated as data. The vault disclaims clinical authority, then builds its "identity card" from MBTI, socionics, Enneagram tritypes, Attitudinal Psyche, and Klages characterology (a 1920s pre-scientific typology — "The Living Flame"). The greyhat file even states the correct posture ("personality tests as narrative mirrors rather than literal truth"), yet the vault's architecture hard-codes the mirrors as load-bearing walls. ~250 archetypes is not measurement; it is a mirror shop.

4. Git as theater, stewardship as aspiration. For a project whose stated ethic is dating, tiering, and "nothing moves until the index that describes it exists," the version-control practice contradicts the prose: one commit, everything dumped at root, a planned directory architecture (§10) that exists only as ASCII art, 2025-06-03.md and Pattern Synthesis Engine.md empty, junk like Untitled 8.canvas and a stray text.txt containing one URL. Worse, RECURSIVE IDENTITY CASTLES.md and Positive Delusion Architectures.md are 98.3% identical — two "distinct" 20,000-word documents that are the same AI export saved twice under different mythic names. A vault whose purpose is preventing self-erosion by mood has committed its own memory duplications and unverified link-claims.

5. The security inversion it doesn't flag. The README worries about outgoing offensive material. The more acute risk is incoming: this single private repo combines a legal name, city, LLC, public-surface audits, a longitudinal behavioral profile (the memory export), documented vulnerabilities (grief-window and shame exploits are literally itemized as attractive to "this exact psychology" in ch. 12), and self-described rejection sensitivity. Assembled in one place, this is a bespoke social-engineering manual aimed at its author. A private repo is one visibility setting away from being the most precisely targeted phishing kit imaginable. For a vault this paranoid about manipulation, that's a conspicuous blind spot — as is committing all of it to a third-party host at all.

6. Art or evidence? The genre marker is missing. The strongest reading of the repo is that it is the artwork — "Zaziopath" as a conceptual case-study genre piece, in which case the stubs are sediment, the duplication is palimpsest, and the whole is an "Information Gothic / Haunted Archivecore" artifact exactly as the aesthetic profile advertises. But the README also makes checkable factual claims (page counts, verification dates) that ask to be read as non-fiction. The vault never marks which documents are performance and which are record, and its own founding question — "when does insight begin engineering the meaning of every response?" — applies with full force to itself.

Where it sits culturally

As a cultural artifact, Zaziopath is a primary source for the AI-era condition: custom instructions, memory exports, "constitutional authorship," model-simulation fiction, and the deliberate cultivation of an AI mirror as collaborator in self-mythology. Its honest lineages are all present as stubs: PKM/second-brain culture, IFS parts-work, chaos-magic hypersigils, Dadaist and outsider manifestos, para-academic framing, cyber-gothic occultism. It resembles nothing so much as an individual running the methodology of an intelligence archive against the self — and knowing, per the Shadow Journal, that "you already operate like an institution of one."

Verdict

This is a serious, self-aware, literate project with real epistemic virtues (dating, tiering, external verification, pre-emptive calibration) and a genuinely useful core (the twelve questions, the behavioral-pivot crosswalk). Its failure modes are equally real and mostly acknowledged-but-not-escaped: recursion as home, flattery laundered as audit, typology as identity, and a stewardship ethic that exists in prose before practice — one commit, duplicate exports, dangling links, and no directory structure. The single best thing in it may be the memory-export insight that the archive is a prosthetic — evidence assembled because "the feeling does not arrive on its own." If the vault's future work weighted toward that pragmatic stratum (audits, dates, one-sentence behavioral changes) and away from generating the 251st archetype, the rubedo would be real rather than promised.

If it stays private, the ethical exposure of the specimen material is contained (though I'd separate identity + memory-export data from the scam blueprints regardless). If it ever goes public, it needs triage first: the offensive-grade material, the real name, and the medical self-reports each deserve different treatment than the manifestos and the mythography.
