"""Build the fictional case report from inspectable repository evidence."""
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from xml.sax.saxutils import escape

OUT = 'CASE_REPORT_THE_UNFILED_RECEIPT.pdf'
navy = colors.HexColor('#14242d'); teal = colors.HexColor('#1e646b'); rust = colors.HexColor('#9e4e36'); pale = colors.HexColor('#edf3f1')
s = getSampleStyleSheet()
s.add(ParagraphStyle(name='KickerX', fontName='Helvetica-Bold', fontSize=8, leading=11, textColor=teal, spaceAfter=10))
s.add(ParagraphStyle(name='TitleX', fontName='Times-Bold', fontSize=28, leading=31, textColor=navy, spaceAfter=11))
s.add(ParagraphStyle(name='DeckX', fontName='Times-Italic', fontSize=12, leading=17, textColor=teal, spaceAfter=16))
s.add(ParagraphStyle(name='HeadX', fontName='Helvetica-Bold', fontSize=12, leading=16, textColor=navy, spaceBefore=13, spaceAfter=7, keepWithNext=True))
s.add(ParagraphStyle(name='BodyX', fontName='Times-Roman', fontSize=10.5, leading=15, textColor=navy, spaceAfter=9))
s.add(ParagraphStyle(name='SmallX', fontName='Helvetica', fontSize=8, leading=11, textColor=navy, spaceAfter=5))
s.add(ParagraphStyle(name='QuoteX', fontName='Times-Italic', fontSize=11, leading=16, textColor=rust, leftIndent=15, rightIndent=12, spaceBefore=8, spaceAfter=12))
s.add(ParagraphStyle(name='MonoX', fontName='Courier', fontSize=8, leading=12, textColor=navy, spaceAfter=5))
P=lambda text,style='BodyX': Paragraph(text,s[style])
story=[]
def footer(c,d):
    c.saveState(); w,h=letter
    c.setStrokeColor(teal); c.line(45,42,w-45,42)
    c.setFont('Helvetica',7.5); c.setFillColor(teal)
    c.drawString(45,29,'ZAZIOPATH / CASE REPORT 26-09 / DOCUMENTARY FICTION')
    c.drawRightString(w-45,29,f'{d.page:02d}'); c.restoreState()
def box(rows,widths):
    t=Table([[P(x,'SmallX') for x in row] for row in rows],colWidths=widths,hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),pale),('BOX',(0,0),(-1,-1),.7,teal),('INNERGRID',(0,0),(-1,-1),.3,colors.HexColor('#b8cac8')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]))
    story.append(t)

story += [P('FILE 26-09  /  CULTURE &amp; SYSTEMS  /  27 SEPTEMBER 2026','KickerX'),P('The unfiled receipt','TitleX'),P('A municipal records clerk reads an art archive as a permit office. The joke holds until she finds a receipt that can leave before it has been filed.','DeckX')]
box([['STATUS','READER','SCOPE'],['Documentary case study; reconstructed dialogue','Mara Vale, fictional temporary clerk, municipal records intake','Repository files only; no browser ledger or private history inspected']],[126,176,220])
story += [P('The wrong desk','HeadX'),P('Vale was asked to index the Zaziopath repository, not interpret it. She had no expertise in music, alchemy or psychology. Her sole question was the kind she asked of permit applications: “Where is the filed copy, and what does the stamp certify?” To the artists and researchers around her, this was a category mistake. The archive described a movement from shadow to signal to stewardship, not a town hall transaction. Its README says a shadow reading that never reaches stewardship is another way of being stuck [1].'),P('Vale disregarded the archetypes and read the buttons. The “missing outbox” in <i>stewardship_receipt.html</i> asks for an action, observable evidence and a date; its form says “File receipt,” and its output ends, “Filed locally in Zaziopath’s stewardship ledger” [2]. The words were bureaucratic enough for her to take literally.'),P('“You cannot issue the certificate from the waiting room,” she said. An archive specialist called it a metaphor. Vale wrote <i>possible premature attestation</i> on a yellow slip and kept reading.','QuoteX'),P('Her test, not her theory','HeadX'),P('She made a two-column register: what a visitor can do before pressing <b>File receipt</b>, and what becomes true only after pressing it. She traced the page’s event listeners, <b>preview()</b>, <b>formatReceipt()</b>, the download button and finally the submit handler. No claim about the maker’s intentions was needed. This is a source-code finding about the page’s available paths, not evidence that anyone used them [2].'),P('FIRST PASS  /  A clerk’s sequence','KickerX'),P('01  Type into either required text field. The input handler calls <b>preview({...buildReceipt()})</b>.','SmallX'),P('02  Preview sets <b>current</b> and enables <b>Download markdown</b>.','SmallX'),P('03  Download serializes <b>current</b> via <b>formatReceipt()</b>; the footer claims the receipt was filed locally.','SmallX'),P('04  Only the separate form-submit handler calls <b>setReceipts([...getReceipts(), r])</b>.','SmallX')]
story.append(PageBreak())
story += [P('CASE REPORT / METHOD &amp; OBJECTIONS','KickerX'),P('Why the experts objected','TitleX'),P('The first objection was sensible: a preview is a draft. The page says so, and the download button may simply let a user save work in progress. It stores nothing on a server; browser storage is a deliberate privacy choice [2]. The second was stronger: nothing in the source proves the ledger is empty in any real person’s browser. The repo’s earlier case study expressly says the ledger’s contents cannot be inferred from the repository [3].'),P('Vale agreed to both. She withdrew her first note, “false receipt,” and replaced it with “attestation available without filing.” The objection did not explain why the preview and downloaded draft share the exact sentence that certifies a filing event. A form can be a private drafting tool; a document that says “Filed locally” is making a different claim.'),P('The one finding','HeadX'),P('In the shipped source, a user can type a character, click <b>Download markdown</b>, and obtain a file whose closing line says it was filed in the local ledger <b>without submitting the form</b>. On this route, <b>setReceipts()</b> is never called [2]. The date comes from an editable date input, and the “observable evidence” is user-entered text; neither is an external attestation. More pointedly, the exported sentence is false even by the application’s own narrow definition of <i>filed</i>.'),P('This is not an allegation of fraud. It is a mismatch between a software state transition and the document’s assertion about that transition. The repository’s Evidence Governance Handbook distinguishes claims from evidence and requires a route to source, transformation and verification state [4]. Here the transformation is visible, but the output does not disclose that it may be an unsubmitted preview.'),box([['ARTIFACT','WHAT IT ESTABLISHES','WHAT IT CANNOT ESTABLISH'],['README.md [1]','The stated endpoint is behavioural stewardship.','Whether any behaviour occurred.'],['stewardship_receipt.html [2]','Preview enables download before submit; exported text says “Filed locally.”','Whether anyone exported a draft.'],['CASE STUDY — The Receipt and the Record.md [3]','Prior reading noted local-only storage.','A particular user’s ledger contents.'],['EVIDENCE_GOVERNANCE_HANDBOOK.md [4]','The archive’s own standard for claim provenance.','That the console intended to certify independently.']],[137,190,195]),P('What changed in the room','HeadX'),P('The archive specialist stopped calling it a category mistake. The software reviewer proposed a harmless fix: label the download <i>Draft</i> until submit, or let the download read only a stored receipt. Vale wanted neither an exposé nor a diagnosis. “A stamp can be private,” she said. “It still has to happen after the event it names.”','QuoteX')]
story.append(PageBreak())
story += [P('CASE REPORT / DISPOSITION','KickerX'),P('A smaller, harder verdict','TitleX'),P('The wrong reader did not solve the artist. She solved a sentence. A sprawling archive had taught its experts to look for symbolic meaning in the word <i>receipt</i>; an unsuitable clerk asked whether the receipt had actually passed through the filing step. The answer, for one export path, was no.'),P('Disposition','HeadX'),P('Finding: <b>reproducible by inspection of the committed client-side code</b>; not browser-tested here. Impact: a downloaded Markdown file can assert local filing when it represents only an unsubmitted preview. Limit: this neither invalidates all receipts nor establishes anything about the author’s conduct. The most conservative correction is to replace the export footer with “Prepared in the local receipt console; filing status not verified,” or to permit export only after submission and serialize the stored record.'),P('What remains unexplained','HeadX'),P('The experts could explain privacy, draft affordances and the decision not to send records to a server. They could not reconcile the categorical past-tense <i>“Filed locally”</i> with a path that never invokes the filing function. That is the discovery—not a secret message, but an assertion stranded one click ahead of its evidence.'),P('Source register / inspected at repository checkout','HeadX'),P('[1] <b>README.md</b>, “Shadow / Signal / Stewardship,” around lines 172–182; receipt-console link around line 621.','SmallX'),P('[2] <b>stewardship_receipt.html</b>, form labels around lines 24–36 and inline script around lines 65–85. Particularly <b>formatReceipt</b>, <b>preview</b>, input listeners, submit listener and download listener.','SmallX'),P('[3] <b>CASE STUDY — The Receipt and the Record.md</b>, “The Scene” and “The Detail That Matters.” Earlier account of local-only records; not independent corroboration of browser use.','SmallX'),P('[4] <b>EVIDENCE_GOVERNANCE_HANDBOOK.md</b>, sections 1–2, claim levels, source types and verification states.','SmallX'),Spacer(1,18),P('EDITORIAL NOTE','KickerX'),P('Mara Vale, the office scene and all dialogue are invented to stage a reproducible code reading. The quoted interface language and code paths are from the repository. This report does not diagnose a person or claim access to any private browser storage.','SmallX')]
SimpleDocTemplate(OUT,pagesize=letter,leftMargin=45,rightMargin=45,topMargin=48,bottomMargin=58,title='The Unfiled Receipt | Case Report',author='Zaziopath case desk').build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
